[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Swegon"
Model = "W4 Smart"
Name = "Ilmanvaihtokone"
SerialNumber = "AA:AA:AA:AA:AA:BB"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesätila, ilmanvaihto"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/summermode.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Takkamoodi"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/fireplace.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesäyöviilennys"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/summercooling.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Tehostus"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/boost.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Ulkolämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh outsideTemp"
polling = 60
minValue = -50


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Syöttölämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh supplyTemperature"
polling = 60
minValue = -50


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Sisälämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh indoorTemperature"
polling = 60
minValue = -30


[[services]]
type = "CarbonDioxideSensor"

[services.characteristics]
Name = "Hiilidioksidipitoisuus"
CarbonDioxidePeakLevel = 900
[services.characteristics.CarbonDioxideDetected]
cmd = "cd ouman; test \"$(./cmd/object.sh co2)\" -gt 650 && echo 1 || echo 0"
polling = 60
[services.characteristics.CarbonDioxideLevel]
cmd = "cd ouman; ./cmd/object.sh co2"
polling = 60


[[services]]
type = "HumiditySensor"

[services.characteristics]
Name = "Suhteellinen kosteus"
[services.characteristics.CurrentRelativeHumidity]
cmd = "cd ouman; ./cmd/object.sh rh"
polling = 60


[[services]]
type = "FanV2"

[services.characteristics]
Name = "Syöttö"
Active = 1
[services.characteristics.RotationSpeed]
cmd = "cd ouman; ./cmd/object.sh supplyFan"
polling = 60
perms = ["pr", "ev"]


[[services]]
type = "FanV2"

[services.characteristics]
Name = "Poisto"
Active = 1
[services.characteristics.RotationSpeed]
cmd = "cd ouman; ./cmd/object.sh exhaustFan"
polling = 60
perms = ["pr", "ev"]
