[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Swegon"
Model = "W4 Smart"
Name = "Ilmanvaihtokone"
SerialNumber = "AA:AA:AA:AA:AA:BB"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesätila, ilmanvaihto"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/summermode.sh"
value = false


[[services]]
type = "Switch"

[services.characteristics]
Name = "Takkamoodi"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/fireplace.sh"
value = false


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesäyöviilennys"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/summercooling.sh"
value = false


[[services]]
type = "Switch"

[services.characteristics]
Name = "Tehostus"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/boost.sh"
value = false


[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Ulkolämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh outsideTemp"
value = 0
minValue = -50


[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Syöttölämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh supplyTemperature"
value = 0


[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Sisälämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh indoorTemperature"
value = 0


[[services]]
type = "CarbonDioxideSensor"
#polling = 60

[services.characteristics]
Name = "Hiilidioksidipitoisuus"
CarbonDioxidePeakLevel = 900
CarbonDioxideDetected = 0
[services.characteristics.CarbonDioxideLevel]
cmd = "cd ouman; ./cmd/object.sh co2"
value = 0


[[services]]
type = "HumiditySensor"
#polling = 60

[services.characteristics]
Name = "Suhteellinen kosteus"
[services.characteristics.CurrentRelativeHumidity]
cmd = "cd ouman; ./cmd/object.sh rh"
value = 0


[[services]]
type = "FanV2"
#polling = 60

[services.characteristics]
Active = 1
Name = "Syöttö"
[services.characteristics.RotationSpeed]
cmd = "cd ouman; ./cmd/object.sh supplyFan"
value = 0


[[services]]
type = "FanV2"
#polling = 60

[services.characteristics]
Active = 1
Name = "Poisto"
[services.characteristics.RotationSpeed]
cmd = "cd ouman; ./cmd/object.sh exhaustFan"
value = 0
