[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Swegon"
Model = "W4 Smart"
Name = "Ilmanvaihtokone"
SerialNumber = "AA:AA:AA:AA:AA:BB"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesätila, ilmanvaihto"
ConfiguredName = "Kesätila, ilmanvaihto"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/summermode.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Takkamoodi"
ConfiguredName = "Takkamoodi"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/fireplace.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesäyöviilennys"
ConfiguredName = "Kesäyöviilennys"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/summercooling.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Tehostus"
ConfiguredName = "Tehostus"
[services.characteristics.On]
cmd = "cd ouman; ./cmd/boost.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Ulkolämpötila"
ConfiguredName = "Ulkolämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh outsideTemp"
minValue = -50


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Syöttölämpötila"
ConfiguredName = "Syöttölämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh supplyTemperature"
minValue = -50


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Sisälämpötila"
ConfiguredName = "Sisälämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd ouman; ./cmd/object.sh indoorTemperature"
minValue = -30


[[services]]
type = "CarbonDioxideSensor"

[services.characteristics]
Name = "Hiilidioksidipitoisuus"
ConfiguredName = "Hiilidioksidipitoisuus"
CarbonDioxidePeakLevel = 900
[services.characteristics.CarbonDioxideDetected]
cmd = "cd ouman; ./cmd/co_detected.sh"
polling = 60
[services.characteristics.CarbonDioxideLevel]
cmd = "cd ouman; ./cmd/object.sh co2"


[[services]]
type = "HumiditySensor"

[services.characteristics]
Name = "Suhteellinen kosteus"
ConfiguredName = "Suhteellinen kosteus"
[services.characteristics.CurrentRelativeHumidity]
cmd = "cd ouman; ./cmd/object.sh rh"


[[services]]
type = "FanV2"

[services.characteristics]
Name = "Syöttö"
ConfiguredName = "Syöttö"
Active = 1
[services.characteristics.RotationSpeed]
cmd = "cd ouman; ./cmd/object.sh supplyFan"


[[services]]
type = "FanV2"

[services.characteristics]
Name = "Poisto"
ConfiguredName = "Poisto"
Active = 1
[services.characteristics.RotationSpeed]
cmd = "cd ouman; ./cmd/object.sh exhaustFan"
